#!/bin/python3
import math
import os
import random
import re
import sys
# Complete the bonAppetit function below.
def bonAppetit(bill, k, b):
    sum=0
    for i in bill:
        if bill.index(i)!=k:
            sum+=i
        else:
            s=bill.index(i)
    if sum/2==b:
        print('Bon Appetit')
    else:
        r=str(bill[s]/2).split('.')
        print(r[0])
        
if __name__ == '__main__':
    nk = input().rstrip().split()
    n = int(nk[0])
    k = int(nk[1])
    bill = list(map(int, input().rstrip().split()))
    b = int(input().strip())
    bonAppetit(bill, k, b)
