#!/bin/python3
import math
import os
import random
import re
import sys
# Complete the breakingRecords function below.
def breakingRecords(scores):
    lb=0;hb=0;r=[]
    for i in range(n):
        if i==0:
            high=scores[0]
            low=scores[0]
        else:
            if scores[i]>high:
                high=scores[i]
                hb+=1
            elif scores[i]<low:
                low=scores[i]
                lb+=1
    r.append(hb)
    r.append(lb)
    return r
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')
    n = int(input())
    scores = list(map(int, input().rstrip().split()))
    result = breakingRecords(scores)
    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')
    fptr.close()
