#!/bin/python3
import math
import os
import random
import re
import sys
# Complete the climbingLeaderboard function below.
def climbingLeaderboard(scores, alice):
    l=[];r=[]
    for i in scores:
        if i  not in l:
            l.append(i)
    l.sort(reverse=True)
    for v in alice:
        l.append(v)
        l.sort(reverse=True)
        temp=l.index(v)
        r.append((temp+1))
        l.pop(temp)
    return r

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')
    scores_count = int(input())
    scores = list(map(int, input().rstrip().split()))
    alice_count = int(input())
    alice = list(map(int, input().rstrip().split()))
    result = climbingLeaderboard(scores, alice)
    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')
    fptr.close()
