#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the countingValleys function below.
def countingValleys(n, s):
    st=0 ; v=0
    for i in s:
        if i =='D' and st==0:
            st-=1
            v+=1
        elif i=='D':
            st-=1
        elif i=='U':
            st+=1
    return v

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    s = input()

    result = countingValleys(n, s)

    fptr.write(str(result) + '\n')

    fptr.close()
