#!/bin/python3
import math
import os
import random
import re
import sys
# Complete the 'diagonalDifference' function below.
#
# The function is expected to return an INTEGER.
# The function accepts 2D_INTEGER_ARRAY arr as parameter.
def diagonalDifference(arr):
    # Write your code here
    sl=0
    sr=0
    t=n-1
    for i in range(n):
        sl+=arr[i][i]
    for j in range(t,-1,-1):
        sr+=arr[j][t-j]
    return abs(sl-sr)
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')
    n = int(input().strip())
    arr = []
    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))
    result = diagonalDifference(arr)
    fptr.write(str(result) + '\n')
    fptr.close()
